name: UpdateLibraries
on:
  workflow_dispatch:
  schedule:
    - cron: '15 14 * * *' # At 1415 daily  
    
jobs:
  check-for-library-changes:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2.3.4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.9 #install the python needed
      - name: execute detail_at.py
        run: |
          pip3 install requests pyyaml
          git config --global user.name 'Library Action'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull
          ./.github/@automation/detail_at.py
          if [ -z "$(git status --porcelain)" ]; then 
            echo 'No changes to commit on this run'
            exit 0
          else
            git commit -am 'Automated libraries.md update from pub.dev'
            git push
          fi
        env:
          GITHUB_API_TOKEN: ${{ secrets.REPO_TOKEN }}